#!/bin/sh
JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl get $1 -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done
