#!/bin/sh

set -xe

usage() { echo "$0 VIRTUALMACHINE"; exit 2 ; }
mirror() { tee /dev/stderr ; }
getYAML() {
if [[ -f "$1" ]]; then
  cat "$1"
else
  kubectl get -o yaml vms ${1:-$(hostname)} ;
fi
}
doit_cond() {
[[ -z "$DRY" ]] && eval "$(cat)" || cat
}

echo Args:
echo $@

echo Starting:
getYAML "$1" \
  | mirror | ./yaml2xml \
  | mirror | xsltproc vmspec2domxml.xslt /dev/stdin \
  | mirror | xsltproc domxml2qemu.xslt /dev/stdin \
  | mirror | doit_cond
