#!/bin/sh

set -xe

usage() { echo "$0 VIRTUALMACHINE"; exit 2 ; }
mirror() { tee /dev/stderr ; }
getYAML() {
if [[ -f "$1" ]]; then
  cat "$1"
else
  kubectl get -o yaml vms ${1:-$(hostname)} ;
fi
}

echo Args:
echo $@

echo Starting:
getYAML "$1" \
  | mirror | ./launch.d/yaml2xml \
  | mirror | xsltproc launch.d/vmspec2domxml.xslt /dev/stdin \
  | mirror | xsltproc launch.d/domxml2qemu.xslt /dev/stdin \
  | mirror > .launchline

cat .launchline

[[ -z "$DRY" ]] && bash .launchline
