#!/bin/env python3

import sys
import xmltodict
import yaml

vm = None
if len(sys.argv) > 1:
    with open(sys.argv[1]) as src:
        vm = src.read()
else:
    vm = sys.stdin.read()

vmdata = yaml.load(vm)

# Dropping these fields because they will lead to slahses in tag names
for k in ["annotations", "labels"]:
    if k in vmdata["metadata"]:
        del vmdata["metadata"][k]

print(xmltodict.unparse({"VirtualMachine": vmdata}, pretty=True))
